services:
  db:
    image: mysql:8.0
    container_name: mysql_curso_da
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT_LOCAL}:3306" #puerto_local:puerto_contenedor
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

#security_opt:
  #- no-new-privileges:false